declare module 'deprecated-react-native-prop-types'
declare module 'react-native-websocket'
declare module 'react-native-smscode-count-down'
declare module 'react-native-tags-input'
// declare module 'react-native-image-picker'