export const INIT_IM = "INIT_IM";
export const REFRESH_CHATLIST = "REFRESH_CHATLIST";
export const CHANGE_LANGUAGE= "CHANGE_LANGUAGE";
export const CHANGE_UNIT= "CHANGE_UNIT";
export const REFRESH_WALLET= "REFRESH_WALLET";
export const LOAD_INITSTATE = "LOAD_INITSTATE";
export const REFRESH_IMUserInfo= "REFRESH_IM_USERINFO";
export const REFRESH_WALLETPWD= "REFRESH_WALLET_PWD";
export const INIT_TOKEN= "INIT_TOKEN";
export const CHANGE_USETOKEN_NAME= "CHANGE_USETOKEN_NAME";
export const GET_TOKENS_INFO= "GET_TOKENS_INFO";
export const CHANGE_CHAIN= "CHANGE_CHAIN";
export const SELECTWALLET= "SELECTWALLET";
export const SET_COMMUNITIES= "SET_COMMUNITIES";

/**REFRESH IM COVERSATION  */
export const IM_LOGIN_IN= "IM_LOGIN_IN";
export const NEEDRELOAD_CHATDETAIL= "NEEDRELOAD_CHATDETAIL";
export const NEEDRELOADCONTACT= "NEEDRELOAD_CONTACT";
export const NEEDRELOADCHATLIST= "NEEDRELOAD_CHATLIST";
export const NEEDRELOADASSETSLIST= "NEEDRELOADASSETSLIST";
export const NEEDRELOAD_MYNFTLIST= "NEEDRELOAD_MYNFTLIST";
export const NEEDRELOAD_INTRODUCE= "NEEDRELOAD_INTRODUCE";
export const NEEDRELOAD_MYTOP= "NEEDRELOAD_MYTOP";

/**Community List */
export const NEEDRELOAD_COMMUNITYLIST= "NEEDRELOAD_COMMUNITYLIST";

