/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  MerchantLockDrop,
  MerchantLockDropInterface,
} from "../MerchantLockDrop";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "AdvanceLock",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "initAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "inToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "outToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "lockPeriod",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "limit",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "logo",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "proIntroduction",
            type: "string",
          },
          {
            internalType: "string",
            name: "tLink",
            type: "string",
          },
          {
            internalType: "string",
            name: "oLink",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct MerchantLockDrop.LockDetail",
        name: "lockDetail",
        type: "tuple",
      },
    ],
    name: "MerchantInitialStruct",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "MerchantWithdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "Unlock",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "merchant",
        type: "address",
      },
    ],
    name: "WithdrawEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "userUri",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "RELEASEUINT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TIMEUINT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adminPoint",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "adminTokenFeeWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "advanceLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "point",
        type: "uint16",
      },
    ],
    name: "changeAdminPoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getLockAt",
    outputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "numOfTokens",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lockEnding",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "releaseToken",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getMerchantLockInfo",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "inToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "outToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "lockPeriod",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "limit",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "logo",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "proIntroduction",
            type: "string",
          },
          {
            internalType: "string",
            name: "tLink",
            type: "string",
          },
          {
            internalType: "string",
            name: "oLink",
            type: "string",
          },
        ],
        internalType: "struct MerchantLockDrop.LockDetail",
        name: "lInfoDetail",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
    ],
    name: "lockERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "inToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "outToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "lockPeriod",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "limit",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "logo",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "proIntroduction",
            type: "string",
          },
          {
            internalType: "string",
            name: "tLink",
            type: "string",
          },
          {
            internalType: "string",
            name: "oLink",
            type: "string",
          },
        ],
        internalType: "struct MerchantLockDrop.LockDetail",
        name: "lockDetail",
        type: "tuple",
      },
    ],
    name: "merchantInitial",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "inToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "outToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "lockPeriod",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "limit",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "logo",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "proIntroduction",
            type: "string",
          },
          {
            internalType: "string",
            name: "tLink",
            type: "string",
          },
          {
            internalType: "string",
            name: "oLink",
            type: "string",
          },
        ],
        internalType: "struct MerchantLockDrop.LockDetail",
        name: "lockDetail",
        type: "tuple",
      },
    ],
    name: "merchantInitialTest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "inToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "outToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "lockPeriod",
            type: "uint16",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inTokenAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenCapacity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "outTokenSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "limit",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "logo",
            type: "string",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "proIntroduction",
            type: "string",
          },
          {
            internalType: "string",
            name: "tLink",
            type: "string",
          },
          {
            internalType: "string",
            name: "oLink",
            type: "string",
          },
        ],
        internalType: "struct MerchantLockDrop.LockDetail",
        name: "lockDetail",
        type: "tuple",
      },
    ],
    name: "merchantInitialTest2",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "merchantWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "unlock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "userUriSet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "numOfTokens",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "releasedToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lockEnding",
            type: "uint256",
          },
        ],
        internalType: "struct MerchantLockDrop.Lock",
        name: "lock",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "vestedAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class MerchantLockDrop__factory {
  static readonly abi = _abi;
  static createInterface(): MerchantLockDropInterface {
    return new utils.Interface(_abi) as MerchantLockDropInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MerchantLockDrop {
    return new Contract(address, _abi, signerOrProvider) as MerchantLockDrop;
  }
}
