/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ProjectInfoStruct = {
  tokenA: string;
  tokenB: string;
  projectText: string;
  projectType: BigNumberish;
  groupID: string;
  startTime: BigNumberish;
  endTime: BigNumberish;
  inTokenCapacity: BigNumberish;
  inTokenAmount: BigNumberish;
  outTokenCapacity: BigNumberish;
  maxExchange: BigNumberish;
  exchange: BigNumberish;
  decimalA: BigNumberish;
  decimalB: BigNumberish;
  lockNum: BigNumberish;
  timeList: BigNumberish[];
};

export type ProjectInfoStructOutput = [
  string,
  string,
  string,
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber[]
] & {
  tokenA: string;
  tokenB: string;
  projectText: string;
  projectType: BigNumber;
  groupID: string;
  startTime: BigNumber;
  endTime: BigNumber;
  inTokenCapacity: BigNumber;
  inTokenAmount: BigNumber;
  outTokenCapacity: BigNumber;
  maxExchange: BigNumber;
  exchange: BigNumber;
  decimalA: BigNumber;
  decimalB: BigNumber;
  lockNum: BigNumber;
  timeList: BigNumber[];
};

export type LockUserStruct = { startTime: BigNumberish; amountB: BigNumberish };

export type LockUserStructOutput = [BigNumber, BigNumber] & {
  startTime: BigNumber;
  amountB: BigNumber;
};

export interface IdoInterface extends utils.Interface {
  functions: {
    "adminAddr()": FunctionFragment;
    "adminPoint()": FunctionFragment;
    "advanceRelease()": FunctionFragment;
    "owner()": FunctionFragment;
    "queryProjectInfo()": FunctionFragment;
    "queryUser()": FunctionFragment;
    "receiveOwner()": FunctionFragment;
    "receiveUser()": FunctionFragment;
    "remainingAmount()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sendAddrA()": FunctionFragment;
    "sendAddrB()": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "swap(uint256)": FunctionFragment;
    "tokenA()": FunctionFragment;
    "tokenB()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "adminAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "advanceRelease",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "queryProjectInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "queryUser", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveUser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remainingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sendAddrA", values?: undefined): string;
  encodeFunctionData(functionFragment: "sendAddrB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "swap", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "tokenA", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "adminAddr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "advanceRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryProjectInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "queryUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendAddrA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendAddrB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "debug(string,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "debug"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type debugEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber],
  {
    name: string;
    msg: string;
    addr: string;
    exec: BigNumber;
    number: BigNumber;
    time: BigNumber;
  }
>;

export type debugEventFilter = TypedEventFilter<debugEvent>;

export interface Ido extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IdoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    adminAddr(overrides?: CallOverrides): Promise<[string]>;

    adminPoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    advanceRelease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    queryProjectInfo(
      overrides?: CallOverrides
    ): Promise<[ProjectInfoStructOutput]>;

    queryUser(overrides?: CallOverrides): Promise<[LockUserStructOutput[]]>;

    receiveOwner(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    receiveUser(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remainingAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendAddrA(overrides?: CallOverrides): Promise<[string]>;

    sendAddrB(overrides?: CallOverrides): Promise<[string]>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      _amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenA(overrides?: CallOverrides): Promise<[string]>;

    tokenB(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  adminAddr(overrides?: CallOverrides): Promise<string>;

  adminPoint(overrides?: CallOverrides): Promise<BigNumber>;

  advanceRelease(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  queryProjectInfo(overrides?: CallOverrides): Promise<ProjectInfoStructOutput>;

  queryUser(overrides?: CallOverrides): Promise<LockUserStructOutput[]>;

  receiveOwner(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  receiveUser(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remainingAmount(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendAddrA(overrides?: CallOverrides): Promise<string>;

  sendAddrB(overrides?: CallOverrides): Promise<string>;

  setFee(
    fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    _amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenA(overrides?: CallOverrides): Promise<string>;

  tokenB(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    adminAddr(overrides?: CallOverrides): Promise<string>;

    adminPoint(overrides?: CallOverrides): Promise<BigNumber>;

    advanceRelease(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    queryProjectInfo(
      overrides?: CallOverrides
    ): Promise<ProjectInfoStructOutput>;

    queryUser(overrides?: CallOverrides): Promise<LockUserStructOutput[]>;

    receiveOwner(overrides?: CallOverrides): Promise<void>;

    receiveUser(overrides?: CallOverrides): Promise<void>;

    remainingAmount(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sendAddrA(overrides?: CallOverrides): Promise<string>;

    sendAddrB(overrides?: CallOverrides): Promise<string>;

    setFee(fee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    swap(_amountIn: BigNumberish, overrides?: CallOverrides): Promise<void>;

    tokenA(overrides?: CallOverrides): Promise<string>;

    tokenB(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "debug(string,address,address,uint256,uint256,uint256)"(
      name?: null,
      msg?: null,
      addr?: null,
      exec?: null,
      number?: null,
      time?: null
    ): debugEventFilter;
    debug(
      name?: null,
      msg?: null,
      addr?: null,
      exec?: null,
      number?: null,
      time?: null
    ): debugEventFilter;
  };

  estimateGas: {
    adminAddr(overrides?: CallOverrides): Promise<BigNumber>;

    adminPoint(overrides?: CallOverrides): Promise<BigNumber>;

    advanceRelease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    queryProjectInfo(overrides?: CallOverrides): Promise<BigNumber>;

    queryUser(overrides?: CallOverrides): Promise<BigNumber>;

    receiveOwner(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    receiveUser(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remainingAmount(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendAddrA(overrides?: CallOverrides): Promise<BigNumber>;

    sendAddrB(overrides?: CallOverrides): Promise<BigNumber>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      _amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenA(overrides?: CallOverrides): Promise<BigNumber>;

    tokenB(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    adminAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adminPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    advanceRelease(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    queryProjectInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    queryUser(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveOwner(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    receiveUser(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remainingAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendAddrA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendAddrB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFee(
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      _amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
