/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type LockDetailStruct = {
  inToken: string;
  outToken: string;
  owner: string;
  lockPeriod: BigNumberish;
  startTime: BigNumberish;
  endTime: BigNumberish;
  inTokenCapacity: BigNumberish;
  inTokenAmount: BigNumberish;
  outTokenCapacity: BigNumberish;
  outTokenSupply: BigNumberish;
  limit: BigNumberish;
  logo: string;
  name: string;
  proIntroduction: string;
  tLink: string;
  oLink: string;
};

export type LockDetailStructOutput = [
  string,
  string,
  string,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  string,
  string,
  string
] & {
  inToken: string;
  outToken: string;
  owner: string;
  lockPeriod: number;
  startTime: BigNumber;
  endTime: BigNumber;
  inTokenCapacity: BigNumber;
  inTokenAmount: BigNumber;
  outTokenCapacity: BigNumber;
  outTokenSupply: BigNumber;
  limit: BigNumber;
  logo: string;
  name: string;
  proIntroduction: string;
  tLink: string;
  oLink: string;
};

export type LockStruct = {
  amount: BigNumberish;
  numOfTokens: BigNumberish;
  releasedToken: BigNumberish;
  lockEnding: BigNumberish;
};

export type LockStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber] & {
  amount: BigNumber;
  numOfTokens: BigNumber;
  releasedToken: BigNumber;
  lockEnding: BigNumber;
};

export interface MerchantLockDropInterface extends utils.Interface {
  functions: {
    "RELEASEUINT()": FunctionFragment;
    "TIMEUINT()": FunctionFragment;
    "adminPoint()": FunctionFragment;
    "adminTokenFeeWithdraw(address)": FunctionFragment;
    "advanceLock(uint256)": FunctionFragment;
    "changeAdminPoint(uint16)": FunctionFragment;
    "getLockAt(address,address,uint256)": FunctionFragment;
    "getMerchantLockInfo(address,uint256)": FunctionFragment;
    "lockERC20(uint256,uint256,address)": FunctionFragment;
    "merchantInitial((address,address,address,uint16,uint256,uint256,uint256,uint256,uint256,uint256,uint256,string,string,string,string,string))": FunctionFragment;
    "merchantInitialTest((address,address,address,uint16,uint256,uint256,uint256,uint256,uint256,uint256,uint256,string,string,string,string,string))": FunctionFragment;
    "merchantInitialTest2((address,address,address,uint16,uint256,uint256,uint256,uint256,uint256,uint256,uint256,string,string,string,string,string))": FunctionFragment;
    "merchantWithdraw(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unlock(uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "userUriSet(string)": FunctionFragment;
    "vestedAmount((uint256,uint256,uint256,uint256),uint256)": FunctionFragment;
    "withdraw(uint256,address)": FunctionFragment;
    "withdrawETH()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "RELEASEUINT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIMEUINT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminTokenFeeWithdraw",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "advanceLock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeAdminPoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockAt",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantLockInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockERC20",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantInitial",
    values: [LockDetailStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantInitialTest",
    values: [LockDetailStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantInitialTest2",
    values: [LockDetailStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "userUriSet", values: [string]): string;
  encodeFunctionData(
    functionFragment: "vestedAmount",
    values: [LockStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "RELEASEUINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIMEUINT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adminPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminTokenFeeWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advanceLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeAdminPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLockAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantLockInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merchantInitial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantInitialTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantInitialTest2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userUriSet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;

  events: {
    "AdvanceLock(address,uint256)": EventFragment;
    "Deposit(address,address,uint256,uint256,uint256)": EventFragment;
    "MerchantInitialStruct(tuple)": EventFragment;
    "MerchantWithdraw(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unlock(address,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "WithdrawEvent(address,uint256,uint256,address)": EventFragment;
    "userUri(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdvanceLock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MerchantInitialStruct"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MerchantWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unlock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "userUri"): EventFragment;
}

export type AdvanceLockEvent = TypedEvent<
  [string, BigNumber],
  { sender: string; index: BigNumber }
>;

export type AdvanceLockEventFilter = TypedEventFilter<AdvanceLockEvent>;

export type DepositEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    sender: string;
    merchant: string;
    index: BigNumber;
    initAmount: BigNumber;
    rewardAmount: BigNumber;
  }
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export type MerchantInitialStructEvent = TypedEvent<
  [LockDetailStructOutput],
  { lockDetail: LockDetailStructOutput }
>;

export type MerchantInitialStructEventFilter =
  TypedEventFilter<MerchantInitialStructEvent>;

export type MerchantWithdrawEvent = TypedEvent<
  [string, BigNumber],
  { sender: string; index: BigNumber }
>;

export type MerchantWithdrawEventFilter =
  TypedEventFilter<MerchantWithdrawEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type PausedEvent = TypedEvent<[string], { account: string }>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export type UnlockEvent = TypedEvent<
  [string, BigNumber],
  { sender: string; index: BigNumber }
>;

export type UnlockEventFilter = TypedEventFilter<UnlockEvent>;

export type UnpausedEvent = TypedEvent<[string], { account: string }>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export type WithdrawEventEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  {
    sender: string;
    rewardAmount: BigNumber;
    index: BigNumber;
    merchant: string;
  }
>;

export type WithdrawEventEventFilter = TypedEventFilter<WithdrawEventEvent>;

export type userUriEvent = TypedEvent<
  [string, string],
  { sender: string; uri: string }
>;

export type userUriEventFilter = TypedEventFilter<userUriEvent>;

export interface MerchantLockDrop extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerchantLockDropInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    RELEASEUINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    TIMEUINT(overrides?: CallOverrides): Promise<[BigNumber]>;

    adminPoint(overrides?: CallOverrides): Promise<[number]>;

    adminTokenFeeWithdraw(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    advanceLock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeAdminPoint(
      point: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLockAt(
      user: string,
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amount: BigNumber;
        numOfTokens: BigNumber;
        lockEnding: BigNumber;
        releaseToken: BigNumber;
      }
    >;

    getMerchantLockInfo(
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [LockDetailStructOutput] & { lInfoDetail: LockDetailStructOutput }
    >;

    lockERC20(
      index: BigNumberish,
      initAmount: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    merchantInitial(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    merchantInitialTest(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    merchantInitialTest2(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    merchantWithdraw(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userUriSet(
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vestedAmount(
      lock: LockStruct,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdraw(
      index: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  RELEASEUINT(overrides?: CallOverrides): Promise<BigNumber>;

  TIMEUINT(overrides?: CallOverrides): Promise<BigNumber>;

  adminPoint(overrides?: CallOverrides): Promise<number>;

  adminTokenFeeWithdraw(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  advanceLock(
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeAdminPoint(
    point: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLockAt(
    user: string,
    merchant: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      amount: BigNumber;
      numOfTokens: BigNumber;
      lockEnding: BigNumber;
      releaseToken: BigNumber;
    }
  >;

  getMerchantLockInfo(
    merchant: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<LockDetailStructOutput>;

  lockERC20(
    index: BigNumberish,
    initAmount: BigNumberish,
    merchant: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  merchantInitial(
    lockDetail: LockDetailStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  merchantInitialTest(
    lockDetail: LockDetailStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  merchantInitialTest2(
    lockDetail: LockDetailStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  merchantWithdraw(
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlock(
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userUriSet(
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vestedAmount(
    lock: LockStruct,
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdraw(
    index: BigNumberish,
    merchant: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawETH(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    RELEASEUINT(overrides?: CallOverrides): Promise<BigNumber>;

    TIMEUINT(overrides?: CallOverrides): Promise<BigNumber>;

    adminPoint(overrides?: CallOverrides): Promise<number>;

    adminTokenFeeWithdraw(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    advanceLock(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    changeAdminPoint(
      point: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getLockAt(
      user: string,
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        amount: BigNumber;
        numOfTokens: BigNumber;
        lockEnding: BigNumber;
        releaseToken: BigNumber;
      }
    >;

    getMerchantLockInfo(
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<LockDetailStructOutput>;

    lockERC20(
      index: BigNumberish,
      initAmount: BigNumberish,
      merchant: string,
      overrides?: CallOverrides
    ): Promise<void>;

    merchantInitial(
      lockDetail: LockDetailStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    merchantInitialTest(
      lockDetail: LockDetailStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    merchantInitialTest2(
      lockDetail: LockDetailStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    merchantWithdraw(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unlock(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    userUriSet(uri: string, overrides?: CallOverrides): Promise<void>;

    vestedAmount(
      lock: LockStruct,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      index: BigNumberish,
      merchant: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawETH(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AdvanceLock(address,uint256)"(
      sender?: string | null,
      index?: null
    ): AdvanceLockEventFilter;
    AdvanceLock(sender?: string | null, index?: null): AdvanceLockEventFilter;

    "Deposit(address,address,uint256,uint256,uint256)"(
      sender?: string | null,
      merchant?: null,
      index?: null,
      initAmount?: null,
      rewardAmount?: null
    ): DepositEventFilter;
    Deposit(
      sender?: string | null,
      merchant?: null,
      index?: null,
      initAmount?: null,
      rewardAmount?: null
    ): DepositEventFilter;

    "MerchantInitialStruct(tuple)"(
      lockDetail?: null
    ): MerchantInitialStructEventFilter;
    MerchantInitialStruct(lockDetail?: null): MerchantInitialStructEventFilter;

    "MerchantWithdraw(address,uint256)"(
      sender?: string | null,
      index?: null
    ): MerchantWithdrawEventFilter;
    MerchantWithdraw(
      sender?: string | null,
      index?: null
    ): MerchantWithdrawEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unlock(address,uint256)"(
      sender?: string | null,
      index?: null
    ): UnlockEventFilter;
    Unlock(sender?: string | null, index?: null): UnlockEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "WithdrawEvent(address,uint256,uint256,address)"(
      sender?: string | null,
      rewardAmount?: null,
      index?: null,
      merchant?: null
    ): WithdrawEventEventFilter;
    WithdrawEvent(
      sender?: string | null,
      rewardAmount?: null,
      index?: null,
      merchant?: null
    ): WithdrawEventEventFilter;

    "userUri(address,string)"(
      sender?: string | null,
      uri?: null
    ): userUriEventFilter;
    userUri(sender?: string | null, uri?: null): userUriEventFilter;
  };

  estimateGas: {
    RELEASEUINT(overrides?: CallOverrides): Promise<BigNumber>;

    TIMEUINT(overrides?: CallOverrides): Promise<BigNumber>;

    adminPoint(overrides?: CallOverrides): Promise<BigNumber>;

    adminTokenFeeWithdraw(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    advanceLock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeAdminPoint(
      point: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLockAt(
      user: string,
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerchantLockInfo(
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockERC20(
      index: BigNumberish,
      initAmount: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    merchantInitial(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    merchantInitialTest(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    merchantInitialTest2(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    merchantWithdraw(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userUriSet(
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vestedAmount(
      lock: LockStruct,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      index: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    RELEASEUINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TIMEUINT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adminPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    adminTokenFeeWithdraw(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    advanceLock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeAdminPoint(
      point: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLockAt(
      user: string,
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMerchantLockInfo(
      merchant: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockERC20(
      index: BigNumberish,
      initAmount: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    merchantInitial(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    merchantInitialTest(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    merchantInitialTest2(
      lockDetail: LockDetailStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    merchantWithdraw(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlock(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userUriSet(
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vestedAmount(
      lock: LockStruct,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      index: BigNumberish,
      merchant: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
